M48
; DRILL file {KiCad 7.0.1} date Thu Jul 20 02:47:47 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-20T02:47:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X122.6Y-46.025
X122.6Y-72.725
X142.45Y-59.807
X149.3Y-46.025
X149.3Y-72.725
T0
M30
